#36 create docker file
sapawarga/phonebook-service pull request #37
Opened 2021-04-16 06:18 UTC by setiadijoe

cc @aldidoanta @firmanJS 
issuenya adalah command yang perlu di dalam docker file untuk deployment

2021-04-16 07:07 UTC, firmanJS commented
Mungkin bisa diskusi sama tim ops untuk tambahan command2 nya @setiadijoe

2021-04-16 07:11 UTC, setiadijoe commented
mungkin aku coba share dulu di wikinya dulu ya

2021-04-16 08:47 UTC, aldidoanta commented
Mantap nuhun @setiadijoe :+1: . Aku sambil coba-coba lagi running Sapawarga existing di local

2021-04-16 08:47 UTC, aldidoanta commented
Mantap nuhun @setiadijoe :+1: . Aku sambil coba-coba lagi running Sapawarga existing di local

2021-04-19 08:15 UTC, setiadijoe commented
> Mantap nuhun @setiadijoe 👍 . Aku sambil coba-coba lagi running Sapawarga existing di local

Gimana do? udah ada insight baru belum?

2021-04-19 10:31 UTC, aldidoanta commented
> > Mantap nuhun @setiadijoe +1 . Aku sambil coba-coba lagi running Sapawarga existing di local
> 
> Gimana do? udah ada insight baru belum?

Blm than, blm sempat lanjut lagi. Minggu ini harus nyisihin waktu buat persiapan Jabar CommIT

2021-04-21 03:16 UTC, setiadijoe commented
jadi ini aku baru update dan coba build dan run containernya lalu muncul error seperti ini
`18712a50950664ac057b108bd020710bec3b64c85549a03d64601a1dd1f1a2b0
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "phonebook-service-grpc": executable file not found in $PATH: unknown.`
minta insightnya ya @jdsteam

2021-04-21 03:35 UTC, setiadijoe commented
> jadi ini aku baru update dan coba build dan run containernya lalu muncul error seperti ini
> `18712a50950664ac057b108bd020710bec3b64c85549a03d64601a1dd1f1a2b0 docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "phonebook-service-grpc": executable file not found in $PATH: unknown.`
> minta insightnya ya @jdsteam

klo sekarang udah bisa dibuild dan udah bisa dirun containernya, tapi statusnya `Exited` minta insgihtnya ya @jdsteam

2021-04-21 09:45 UTC, firmanJS approved these changes

2021-04-21 09:58 UTC, setiadijoe commented
@azophy

2021-04-23 04:00 UTC, yohang88 requested changes
Cekidot yesss 😁

2021-04-23 04:00 UTC, yohang88 commented on docker-compose.yml
> +      - MYSQL_USER=nathan
ini juga jangan pakai `nathan` 😁

2021-04-23 04:07 UTC, yohang88 commented on docker-compose.yml
> +  database:
Ini 1 service perlu create service database mysql juga? Service lain nanti juga akan perlu create database?

2021-04-23 04:43 UTC, firmanJS commented on docker-compose.yml
> +  database:
kallo menurut aku jika udah microservices tidak perlu create services mysql di docker-compose nya CMIW :running_man:

2021-04-23 07:04 UTC, setiadijoe commented on docker-compose.yml
> +  database:
ini tadi uji coba dulu sih, ini lagi mau diberesin lagi

2021-04-23 08:01 UTC, setiadijoe reviewed
untuk saat ini terkait maintainability issuenya akan diselesaikan di issue yang berbeda di issue nomor #40

2021-04-26 02:52 UTC, firmanJS approved these changes

2021-04-26 03:03 UTC, rindibudiaramdhan commented on docker-compose.yml
> +  #     - .env
ini masih digunakan untuk koneksi ke databasenya kang @setiadijoe ?

2021-04-26 03:04 UTC, setiadijoe commented on Dockerfile
> +COPY .env ./.env
ooh iya mang bener, nanti diupdate lagi

2021-04-26 03:06 UTC, setiadijoe commented on docker-compose.yml
> +  #     - .env
untuk kasus yang saat ini karena share database, jadi masih pakai koneksi yang sama. Kita kan approach level microservicenya masih di tahap logic nya belum sampai memisahkan dbnya juga. Nah kalau memang mau ada pemisahan db ke depannya nanti perlu ada bahasan lebih lanjut lagi mang

2021-04-26 03:07 UTC, aldidoanta approved these changes

2021-04-26 03:22 UTC, merged