#74 update query get detail, add build-push action
sapawarga/phonebook-service pull request #75
Opened 2021-07-27 09:26 UTC by setiadijoe

close #74

2021-07-28 02:14 UTC, firmanJS approved these changes

2021-07-28 03:16 UTC, yohang88 requested changes
Great @setiadijoe, thank you 🚀  👍 

There're 3 minor comments yes, please check 😁

2021-07-28 03:16 UTC, yohang88 commented on .github/workflows/build-push.yml
> +      - 'phonebook-service/**'
This `path` is not necessary because this was single-repo (not mono-repo with multiple services). 😁

2021-07-28 03:16 UTC, yohang88 commented on .github/workflows/build-push.yml
> +        file: phonebook-service/Dockerfile
This `context` and `file` is also not necessary, because Dockerfile was on the root directory. 😁

2021-07-28 03:16 UTC, yohang88 commented on .github/workflows/build-push.yml
> +        docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
For more generic template, change:
```
HARBOR_URL to REGISTRY_URL
HARBOR_USERNAME to REGISTRY_USERNAME
HARBOR_PASSWORD to REGISTRY_PASSWORD
```

Make sure you already set this environment variables/secret on Github Repository settings 😁

2021-07-28 03:36 UTC, setiadijoe commented
I have create secret repository @yohang88

2021-07-28 06:34 UTC, yohang88 commented on .github/workflows/build-push.yml
> +        tags: ${{ secrets.SERVICE_PHONEBOOK_IMAGENAME }}:${{ steps.vars.outputs.sha_short }}
Last thing, you need discuss with Devops @smilelikeshit about docker image name (example: `registry.digitalservice.id/sapawarga/service-phonebook`)

2021-07-29 03:36 UTC, setiadijoe commented on .github/workflows/build-push.yml
> +        tags: ${{ secrets.SERVICE_PHONEBOOK_IMAGENAME }}:${{ steps.vars.outputs.sha_short }}
has been added secret for `SERVICE_PHONEBOOK_IMAGENAME`

2021-07-29 04:18 UTC, setiadijoe commented on .github/workflows/build-push.yml
> +        tags: ${{ secrets.SERVICE_PHONEBOOK_IMAGENAME }}:${{ steps.vars.outputs.sha_short }}
@yohang88

2021-07-29 04:29 UTC, yohang88 approved these changes

2021-07-29 04:29 UTC, yohang88 commented on .github/workflows/build-push.yml
> +        tags: ${{ secrets.SERVICE_PHONEBOOK_IMAGENAME }}:${{ steps.vars.outputs.sha_short }}
guddd thank you @setiadijoe @smilelikeshit

2021-07-29 04:34 UTC, merged